version: '3'
services:
    unicornpaint:
        build: .
        image: mfashby/unicornpaint
        ports: 
            - "3001:3001"
        volumes:
            - "/dev/spidev0.0:/dev/spidev0.0"
            - "/home/pi/docker/unicornpaint/saves/:/saves/"
